# COCO 80 classes mapping to Vietnamese
COCO_MAPPING_VIETNAMESE = {
    "person": "Người",
    "bicycle": "Xe đạp",
    "car": "Ô tô",
    "motorcycle": "Xe máy",
    "airplane": "Máy bay",
    "bus": "Xe buýt",
    "train": "Tàu hỏa",
    "truck": "Xe tải",
    "boat": "Thuyền",
    "traffic light": "Đèn giao thông",
    "fire hydrant": "Vòi cứu hỏa",
    "stop sign": "Biển dừng",
    "parking meter": "Bộ đo bãi đỗ",
    "bench": "Ghế dài",
    "bird": "Chim",
    "cat": "Mèo",
    "dog": "Chó",
    "horse": "Ngựa",
    "sheep": "Cừu",
    "cow": "Bò",
    "elephant": "Voi",
    "bear": "Gấu",
    "zebra": "Ngựa vằn",
    "giraffe": "Hươu cao cổ",
    "backpack": "Ba lô",
    "umbrella": "Ô",
    "handbag": "Túi xách",
    "tie": "Cravat",
    "suitcase": "Vali",
    "frisbee": "Đĩa bay",
    "skis": "Ván trượt tuyết",
    "snowboard": "Ván lướt tuyết",
    "sports ball": "Bóng thể thao",
    "kite": "Diều",
    "baseball bat": "Gậy bóng chày",
    "baseball glove": "Găng tay bóng chày",
    "skateboard": "Ván trượt",
    "surfboard": "Ván lướt sóng",
    "tennis racket": "Vợt tennis",
    "bottle": "Chai",
    "wine glass": "Ly rượu",
    "cup": "Ly",
    "fork": "Nĩa",
    "knife": "Dao",
    "spoon": "Muỗng",
    "bowl": "Bát",
    "banana": "Chuối",
    "apple": "Táo",
    "sandwich": "Bánh sandwich",
    "orange": "Cam",
    "broccoli": "Bông cải xanh",
    "carrot": "Cà rốt",
    "hot dog": "Bánh nóng",
    "pizza": "Pizza",
    "donut": "Bánh donut",
    "cake": "Bánh",
    "chair": "Ghế",
    "couch": "Ghế sofa",
    "potted plant": "Cây trong chậu",
    "bed": "Giường",
    "dining table": "Bàn ăn",
    "toilet": "Bồn cầu",
    "tv": "Tivi",
    "laptop": "Máy tính xách tay",
    "mouse": "Chuột máy tính",
    "remote": "Điều khiển từ xa",
    "keyboard": "Bàn phím",
    "cell phone": "Điện thoại di động",
    "microwave": "Lò vi sóng",
    "oven": "Lò nướng",
    "toaster": "Máy nướng bánh",
    "sink": "Bồn rửa",
    "refrigerator": "Tủ lạnh",
    "book": "Sách",
    "clock": "Đồng hồ",
    "vase": "Bình hoa",
    "scissors": "Kéo",
    "teddy bear": "Gấu bông",
    "hair drier": "Máy sấy tóc",
    "toothbrush": "Bàn chải đánh răng",
}


def translate_coco_class_name(class_name: str) -> str:
    """Dịch COCO class name sang tiếng Việt"""
    return COCO_MAPPING_VIETNAMESE.get(class_name, class_name)
